cource/urls.py
from django.urls import path

from .import views

app_name = 'cource'

urlpatterns = [
    path('',views.home,name="home"),
    path('index/',views.index,name="index"),
    path('register/',views.register,name="register"),
    path('register_data/',views.register_data,name="register_data"),
    path('login_data/',views.login_data,name="login_data"),
    path('home/',views.home,name="home"),
    path('logout_user/',views.logout_user,name="logout_user"),
    path('add_cource/',views.add_cource,name="add_cource"),
    path('cource_data/',views.cource_data,name="cource_data"),
    path('search/',views.search,name="search"),
    path('update_cource/',views.update_cource,name="update_cource"),
    path('update_value/<int:id>/',views.update_value,name="update_value"),
    path('delete_cource/<int:id>/',views.delete_cource,name="delete_cource"),


]

cource_management/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cource.urls'))
]

cource/models.py
from django.db import models

# Create your models here.


class Cource(models.Model):
    title = models.CharField(max_length=50,null=True)
    description = models.TextField()
    instructor = models.CharField(max_length=100,null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    capacity = models.IntegerField()

    def __str__(self):
        return self.title

cource/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator

from .models import Cource

# Create your views here.

def home(request):
    data = Cource.objects.all()
    paginator = Paginator(data,5)
    page = request.GET.get('page')
    paged_data = paginator.get_page(page)

    context = {'course':paged_data}
    return render(request, 'home.html',context)

def index(request):
    return render(request, 'index.html')

def register(request):
    return render(request,'register.html')

def register_data(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        try:
            user = User.objects.create_user(username,email,password)
            user.save()
            return redirect('cource:index')
        except:
            return render(request,'register.html') 
    else:
        return render(request,'register.html')
    
def login_data(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(username = username, password = password)

        if user is not None:
            login(request,user)
            return redirect('cource:home')
        else:
            return render(request,'index.html')
    else:
        return render(request,'index.html')

def logout_user(request):
    logout(request)
    return render(request,'index.html') 
  


def add_cource(request):
    return render(request,'addcource.html')

def cource_data(request):
    if request.method == 'POST':
        
        title =       request.POST['title']
        description = request.POST['description']
        instructor =  request.POST['instructor']
        startdate =   request.POST['startdate']
        enddate =     request.POST['enddate']
        capacity =    request.POST['capacity']
        try:
            cource = Cource.objects.create(
                title = title,
                description = description,
                instructor = instructor,
                start_date = startdate,
                end_date = enddate,
                capacity = capacity
            )

            cource.save()
            return redirect('cource:home')
        except:
            return render(request,'addcource.html')
    else:
        return render(request,'addcource.html')

def search(request):
    if request.method == 'POST':
        title = request.POST['title_search']

        try:
            course = Cource.objects.filter(title__icontains = title)
        except:
            return redirect('cource:home')
        context = {'course':course}

        return render(request,'home.html',context)
    else:
        return redirect('cource:home')
    

def update_cource(request):
    data = Cource.objects.all()

    context = {'course':data}
    return render(request,'updatecource.html',context)

def update_value(request,id):
    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']
        instructor = request.POST['instructor']
        startdate = request.POST['startdate']
        enddate = request.POST['enddate']
        capacity = request.POST['capacity']

        try:
            data = Cource.objects.get(id=id)

            data.title = title
            data.description = description
            data.instructor = instructor
            data.start_date = startdate
            data.end_date = enddate
            data.capacity = capacity
            data.save(update_fields=['title','description','instructor','start_date','end_date','capacity'])
            return redirect('cource:update_cource')

        except:
            return redirect('cource:update_cource')
    else:
        return redirect('cource:update_cource')

def delete_cource(request,id):
    try:
        cource = Cource.objects.get(id=id)
        print(cource)
        cource.delete()
        return redirect('cource:update_cource')
    except:
        return redirect('cource:update_cource')
        

templates/addcource.html
{% extends "base.html" %}

{% block content %}
<h2 class="text-center">Add Course</h2>
<div class="container w-50">
    <form action = "{% url "cource:cource_data" %}" method = 'POST'>
        {% csrf_token %}
    <div class="form-group py-2">
        <label for="exampleFormControlInput1">Title</label>
        <input type="text" name="title" class="form-control" id="exampleFormControlInput1">
    </div>
  
    <div class="form-group py-2">
        <label for="exampleFormControlTextarea1">Example textarea</label>
    <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
        <div class="form-group py-2">
        <label for="exampleFormControlInput1">Instructor</label>
        <input type="text" name="instructor" class="form-control" id="exampleFormControlInput1">
    </div>
    <div class="form-group py-2">
        <label for="exampleFormControlInput1">Start date</label>
        <input type="date" name="startdate" class="form-control" id="exampleFormControlInput1">
    </div>
    <div class="form-group py-2">
        <label for="exampleFormControlInput1">End date</label>
        <input type="date" name="enddate" class="form-control" id="exampleFormControlInput1">
    </div>
    <div class="form-group py-2">
        <label for="exampleFormControlInput1">Capacity</label>
        <input type="number" name="capacity" class="form-control" id="exampleFormControlInput1">
    </div>
    <div class="d-grid gap-2 py-4">
        <button class="btn btn-primary" type="submit">Add Cource</button>
      </div>

    </form>
</div>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url "cource:home" %}">Course Management</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url "cource:home" %}">Home</a>
              
              {% if user.is_authenticated %}
                <a class="nav-link" href="{% url "cource:logout_user" %}">Logout</a>
              {% else %}
                <a class="nav-link" href="{% url "cource:register" %}">Register</a>
                <a class="nav-link" href="{% url "cource:index" %}">Login</a>
              {% endif %}

              {% if user.is_superuser %}
                <a class="nav-link" href="{% url "cource:add_cource" %}">Add cource</a>
                <a class="nav-link" href="{% url "cource:update_cource" %}">Update cource details</a>
              {% endif %}
              
            </div>
          </div>
        </div>
      </nav>
      {% block content %}
      
      {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}




<div class="container">
    <h2 class="text-center py-3">Courses Offered</h2>
    <form action = "{% url "cource:search" %}" method = 'POST' class="form-inline py-4 d-flex justify-content-center md-form form-sm mt-0">
        {% csrf_token %}
        <i class="fas fa-search" aria-hidden="true"></i>
        <input class="form-control form-control-sm ml-3 w-75" name="title_search" type="text" placeholder="Enter title" aria-label="Search">
    </form>
    <table class="table">
        <thead>
        <tr>
            
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Instructor</th>
            <th scope="col">Start date</th>
            <th scope="col">End date</th>
            <th scope="col">Capacity</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for i in course %}
        <tr>
            
            <td>{{i.title}}</td>
            <td><input class="form-control input-lg w-100  overflow-scroll" type = "text" value = "{{i.description}}" disabled></td>
            <td>{{i.instructor}}</td>
            <td>{{i.start_date}}</td>
            <td>{{i.end_date}}</td>
            <td>{{i.capacity}}</td>
        </tr>
        {% endfor %}
    
        </tbody>
    </table>
</div>

<nav aria-label="Page navigation example">
  {% if course.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% if course.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page = {{course.previous_page_number}}" tabindex="-1" aria-disabled="true">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
      </li>
      {% endif %}

      {% for i in course.paginator.page_range %}
        {% if course.number == i %}
            <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
        {% endif %}
      {% endfor %}

      {% if course.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page = {{course.next_page_number}}" tabindex="-1" aria-disabled="true">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
      </li>
      {% endif %}
    </ul>
  {% endif %}
  </nav>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<h2 class="text-center">Login</h2>

<div class="container w-25">
<form action="{% url 'cource:login_data' %}" method = 'POST'>
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Username</label>
      <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input type="password" name="password" class="form-control" id="exampleInputPassword1">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  Doesn't have an account? <a href="{% url "cource:register" %}">register</a>
</div>


{% endblock content %}

templates/register.html
{% extends "base.html" %}

{% block content %}

<h2 class="text-center">Register</h2>

<div class="container w-25">
<form action = "{% url "cource:register_data" %}" method = 'POST'>
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputEmail1"  class="form-label">Username</label>
      <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
      
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Email</label>
      <input type="email" name="email" class="form-control" id="exampleInputPassword1">
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
      </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  
</div>
{% endblock%}

templates/updatecource.html
{% extends "base.html" %}

{% block content %}




<div class="container">
    <h2 class="text-center py-3">Courses Offered</h2>
    <table class="table">
        <thead>
        <tr>
            
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Instructor</th>
            <th scope="col">Start date</th>
            <th scope="col">End date</th>
            <th scope="col">Capacity</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for i in course %}
        <tr>
            <form action = "{% url "cource:update_value" i.id %}" method = 'POST'>
                {% csrf_token %}
            <td><input name="title" type="text" value = "{{i.title}}"  class="form-control"></td>
            <td><input name="description" class="form-control input-lg w-100  overflow-scroll" type = "textarea" value = "{{i.description}}"></td>
            <td><input name="instructor" type="text" value = "{{i.instructor}}"  class="form-control"></td>
            <td><input name="startdate" type="date" value = "{{i.start_date|date:'Y-m-d' }}"  class="form-control"></td>
            <td><input name="enddate" type="date" value = "{{i.end_date|date:'Y-m-d'}}" class="form-control"></td>
            <td><input name="capacity" type="number" value = "{{i.capacity}}"  class="form-control"></td>
            <td><button class="btn btn-primary" type="submit">Update</button></td>
            </form>
            <td><a href="{% url "cource:delete_cource" i.id %}" class="btn btn-primary">Delete</a></td>
        </tr>
        {% endfor %}
    
        </tbody>
    </table>
</div>

{% endblock %}